name: Deploy Flask App to AWS Lambda

on:
  push:
    branches:
      - main  # Triggers deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version  # Verify installation

      - name: Install Dependencies
        run: |
          pip install --target package -r requirements.txt
          cp app.py package/
          echo '{"LambdaHandler": "app.lambda_handler"}' > package/runtime-config.json

      - name: Package Lambda
        run: |
          cd package
          zip -r ../deployment.zip .

      - name: Create Lambda Function If It Does Not Exist
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
        run: |
          FUNCTION_NAME="flask-auth-app"
          ROLE_ARN="arn:aws:iam::296048193302:role/YOUR_LAMBDA_ROLE"

          # Check if function exists
          if ! aws lambda get-function --function-name $FUNCTION_NAME --region $AWS_REGION; then
            echo "Lambda function does not exist. Creating..."
            aws lambda create-function \
              --function-name $FUNCTION_NAME \
              --runtime python3.9 \
              --role $ROLE_ARN \
              --handler app.lambda_handler \
              --timeout 30 \
              --memory-size 256 \
              --package-type Zip \
              --zip-file fileb://deployment.zip \
              --region $AWS_REGION
          else
            echo "Lambda function exists. Updating..."
            aws lambda update-function-code \
              --function-name $FUNCTION_NAME \
              --zip-file fileb://deployment.zip \
              --region $AWS_REGION
          fi

      - name: Enable Lambda Function URL
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
        run: |
          aws lambda add-permission \
            --function-name flask-auth-app \
            --statement-id function-url \
            --action lambda:InvokeFunctionUrl \
            --principal '*' \
            --region $AWS_REGION
