name: Deploy HTML to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          mkdir package
          cp -r app package/
          cp app.py package/

      - name: Package Lambda
        run: |
          cd package
          zip -r ../deployment.zip .

      - name: Deploy to Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
        run: |
          aws lambda update-function-code \
            --function-name flask-auth-app \
            --zip-file fileb://deployment.zip \
            --region $AWS_REGION
